image: markhobson/maven-chrome:latest

stages:
  - build
  - test
  - report

compile:
  stage: build
  script:
    - mvn -ntp compile
  artifacts:
    paths:
      - target

frontend-test:
  stage: test
  script:
    - mvn -ntp test -Dtest=runner.FrontendTestsRunner
  dependencies:
    - compile
  artifacts:
    when: always
    paths:
      - target
  allow_failure: true

backend-test:
  stage: test
  script:
    - mvn -ntp test -Dtest=runner.BackendTestsRunner
  dependencies:
    - compile
  artifacts:
    when: always
    paths:
      - target
  allow_failure: true

report:
  stage: report
  script:
    - mvn -ntp serenity:aggregate
  artifacts:
    paths:
      - target/site/serenity/
  dependencies:
    - backend-test
    - frontend-test